# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetGkePoliciesDataSourceResult',
    'AwaitableGetGkePoliciesDataSourceResult',
    'get_gke_policies_data_source',
    'get_gke_policies_data_source_output',
]

@pulumi.output_type
class GetGkePoliciesDataSourceResult:
    """
    A collection of values returned by GetGkePoliciesDataSource.
    """
    def __init__(__self__, features=None, id=None, policies=None):
        if features and not isinstance(features, dict):
            raise TypeError("Expected argument 'features' to be a dict")
        pulumi.set(__self__, "features", features)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if policies and not isinstance(policies, list):
            raise TypeError("Expected argument 'policies' to be a list")
        pulumi.set(__self__, "policies", policies)

    @_builtins.property
    @pulumi.getter
    def features(self) -> Optional[Mapping[str, _builtins.bool]]:
        return pulumi.get(self, "features")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def policies(self) -> Sequence[_builtins.str]:
        return pulumi.get(self, "policies")


class AwaitableGetGkePoliciesDataSourceResult(GetGkePoliciesDataSourceResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetGkePoliciesDataSourceResult(
            features=self.features,
            id=self.id,
            policies=self.policies)


def get_gke_policies_data_source(features: Optional[Mapping[str, _builtins.bool]] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetGkePoliciesDataSourceResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['features'] = features
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('castai:gcp:GetGkePoliciesDataSource', __args__, opts=opts, typ=GetGkePoliciesDataSourceResult).value

    return AwaitableGetGkePoliciesDataSourceResult(
        features=pulumi.get(__ret__, 'features'),
        id=pulumi.get(__ret__, 'id'),
        policies=pulumi.get(__ret__, 'policies'))
def get_gke_policies_data_source_output(features: Optional[pulumi.Input[Optional[Mapping[str, _builtins.bool]]]] = None,
                                        opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetGkePoliciesDataSourceResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['features'] = features
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('castai:gcp:GetGkePoliciesDataSource', __args__, opts=opts, typ=GetGkePoliciesDataSourceResult)
    return __ret__.apply(lambda __response__: GetGkePoliciesDataSourceResult(
        features=pulumi.get(__response__, 'features'),
        id=pulumi.get(__response__, 'id'),
        policies=pulumi.get(__response__, 'policies')))
