# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['OrganizationMembersArgs', 'OrganizationMembers']

@pulumi.input_type
class OrganizationMembersArgs:
    def __init__(__self__, *,
                 organization_id: pulumi.Input[_builtins.str],
                 members: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 viewers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a OrganizationMembers resource.
        :param pulumi.Input[_builtins.str] organization_id: CAST AI organization ID.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] members: A list of email addresses corresponding to users who should be given member access to the organization.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] owners: A list of email addresses corresponding to users who should be given owner access to the organization.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] viewers: A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        pulumi.set(__self__, "organization_id", organization_id)
        if members is not None:
            warnings.warn("""The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""", DeprecationWarning)
            pulumi.log.warn("""members is deprecated: The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
        if members is not None:
            pulumi.set(__self__, "members", members)
        if owners is not None:
            warnings.warn("""The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""", DeprecationWarning)
            pulumi.log.warn("""owners is deprecated: The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
        if owners is not None:
            pulumi.set(__self__, "owners", owners)
        if viewers is not None:
            warnings.warn("""The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""", DeprecationWarning)
            pulumi.log.warn("""viewers is deprecated: The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
        if viewers is not None:
            pulumi.set(__self__, "viewers", viewers)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Input[_builtins.str]:
        """
        CAST AI organization ID.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def members(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of email addresses corresponding to users who should be given member access to the organization.
        """
        return pulumi.get(self, "members")

    @members.setter
    def members(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "members", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def owners(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of email addresses corresponding to users who should be given owner access to the organization.
        """
        return pulumi.get(self, "owners")

    @owners.setter
    def owners(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "owners", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def viewers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        return pulumi.get(self, "viewers")

    @viewers.setter
    def viewers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "viewers", value)


@pulumi.input_type
class _OrganizationMembersState:
    def __init__(__self__, *,
                 members: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 organization_id: Optional[pulumi.Input[_builtins.str]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 viewers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering OrganizationMembers resources.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] members: A list of email addresses corresponding to users who should be given member access to the organization.
        :param pulumi.Input[_builtins.str] organization_id: CAST AI organization ID.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] owners: A list of email addresses corresponding to users who should be given owner access to the organization.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] viewers: A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        if members is not None:
            warnings.warn("""The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""", DeprecationWarning)
            pulumi.log.warn("""members is deprecated: The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
        if members is not None:
            pulumi.set(__self__, "members", members)
        if organization_id is not None:
            pulumi.set(__self__, "organization_id", organization_id)
        if owners is not None:
            warnings.warn("""The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""", DeprecationWarning)
            pulumi.log.warn("""owners is deprecated: The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
        if owners is not None:
            pulumi.set(__self__, "owners", owners)
        if viewers is not None:
            warnings.warn("""The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""", DeprecationWarning)
            pulumi.log.warn("""viewers is deprecated: The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
        if viewers is not None:
            pulumi.set(__self__, "viewers", viewers)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def members(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of email addresses corresponding to users who should be given member access to the organization.
        """
        return pulumi.get(self, "members")

    @members.setter
    def members(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "members", value)

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        CAST AI organization ID.
        """
        return pulumi.get(self, "organization_id")

    @organization_id.setter
    def organization_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization_id", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def owners(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of email addresses corresponding to users who should be given owner access to the organization.
        """
        return pulumi.get(self, "owners")

    @owners.setter
    def owners(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "owners", value)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def viewers(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        return pulumi.get(self, "viewers")

    @viewers.setter
    def viewers(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "viewers", value)


@pulumi.type_token("castai:organization:OrganizationMembers")
class OrganizationMembers(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 members: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 organization_id: Optional[pulumi.Input[_builtins.str]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 viewers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a OrganizationMembers resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] members: A list of email addresses corresponding to users who should be given member access to the organization.
        :param pulumi.Input[_builtins.str] organization_id: CAST AI organization ID.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] owners: A list of email addresses corresponding to users who should be given owner access to the organization.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] viewers: A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OrganizationMembersArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OrganizationMembers resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param OrganizationMembersArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OrganizationMembersArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 members: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 organization_id: Optional[pulumi.Input[_builtins.str]] = None,
                 owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 viewers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OrganizationMembersArgs.__new__(OrganizationMembersArgs)

            __props__.__dict__["members"] = members
            if organization_id is None and not opts.urn:
                raise TypeError("Missing required property 'organization_id'")
            __props__.__dict__["organization_id"] = organization_id
            __props__.__dict__["owners"] = owners
            __props__.__dict__["viewers"] = viewers
        super(OrganizationMembers, __self__).__init__(
            'castai:organization:OrganizationMembers',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            members: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            organization_id: Optional[pulumi.Input[_builtins.str]] = None,
            owners: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            viewers: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'OrganizationMembers':
        """
        Get an existing OrganizationMembers resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] members: A list of email addresses corresponding to users who should be given member access to the organization.
        :param pulumi.Input[_builtins.str] organization_id: CAST AI organization ID.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] owners: A list of email addresses corresponding to users who should be given owner access to the organization.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] viewers: A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrganizationMembersState.__new__(_OrganizationMembersState)

        __props__.__dict__["members"] = members
        __props__.__dict__["organization_id"] = organization_id
        __props__.__dict__["owners"] = owners
        __props__.__dict__["viewers"] = viewers
        return OrganizationMembers(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'members' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def members(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of email addresses corresponding to users who should be given member access to the organization.
        """
        return pulumi.get(self, "members")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> pulumi.Output[_builtins.str]:
        """
        CAST AI organization ID.
        """
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'owners' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def owners(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of email addresses corresponding to users who should be given owner access to the organization.
        """
        return pulumi.get(self, "owners")

    @_builtins.property
    @pulumi.getter
    @_utilities.deprecated("""The 'viewers' field is deprecated. Use 'castai_role_bindings' resource instead for more granular role management. This field will be removed in a future version.""")
    def viewers(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of email addresses corresponding to users who should be given viewer access to the organization.
        """
        return pulumi.get(self, "viewers")

