// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Rebalancing.Inputs
{

    public sealed class HibernationSchedulePauseConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enables or disables the pause configuration.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        [Input("schedule", required: true)]
        public Input<Inputs.HibernationSchedulePauseConfigScheduleArgs> Schedule { get; set; } = null!;

        public HibernationSchedulePauseConfigArgs()
        {
        }
        public static new HibernationSchedulePauseConfigArgs Empty => new HibernationSchedulePauseConfigArgs();
    }
}
