// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Rebalancing.Inputs
{

    public sealed class HibernationScheduleResumeConfigJobConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodeConfig", required: true)]
        public Input<Inputs.HibernationScheduleResumeConfigJobConfigNodeConfigArgs> NodeConfig { get; set; } = null!;

        public HibernationScheduleResumeConfigJobConfigArgs()
        {
        }
        public static new HibernationScheduleResumeConfigJobConfigArgs Empty => new HibernationScheduleResumeConfigJobConfigArgs();
    }
}
