// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Rebalancing.Inputs
{

    public sealed class HibernationScheduleResumeConfigJobConfigNodeConfigVolumeArgs : global::Pulumi.ResourceArgs
    {
        [Input("raidConfigs")]
        private InputList<Inputs.HibernationScheduleResumeConfigJobConfigNodeConfigVolumeRaidConfigArgs>? _raidConfigs;
        public InputList<Inputs.HibernationScheduleResumeConfigJobConfigNodeConfigVolumeRaidConfigArgs> RaidConfigs
        {
            get => _raidConfigs ?? (_raidConfigs = new InputList<Inputs.HibernationScheduleResumeConfigJobConfigNodeConfigVolumeRaidConfigArgs>());
            set => _raidConfigs = value;
        }

        /// <summary>
        /// Volume size in GiB.
        /// </summary>
        [Input("sizeGib")]
        public Input<int>? SizeGib { get; set; }

        public HibernationScheduleResumeConfigJobConfigNodeConfigVolumeArgs()
        {
        }
        public static new HibernationScheduleResumeConfigJobConfigNodeConfigVolumeArgs Empty => new HibernationScheduleResumeConfigJobConfigNodeConfigVolumeArgs();
    }
}
