version: 2
updates:
  # Main go.mod
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # Only allow security updates for specific packages
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    # Specify which dependencies to update
    allow:
      - dependency-name: "github.com/go-git/go-git/v5"
        dependency-type: "direct"
      - dependency-name: "golang.org/x/crypto"
        dependency-type: "direct"
    # Ignore local module references
    ignore:
      - dependency-name: "github.com/castai/pulumi-castai/*"

  # Provider module
  - package-ecosystem: "gomod"
    directory: "/provider"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    allow:
      - dependency-name: "github.com/go-git/go-git/v5"
        dependency-type: "direct"
      - dependency-name: "golang.org/x/crypto"
        dependency-type: "direct"
    ignore:
      - dependency-name: "github.com/castai/pulumi-castai/*"

  # We no longer use the /sdk/go directory, only /sdk/go/castai

  # SDK/castai module
  - package-ecosystem: "gomod"
    directory: "/sdk/go/castai"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    allow:
      - dependency-name: "github.com/go-git/go-git/v5"
        dependency-type: "direct"
      - dependency-name: "golang.org/x/crypto"
        dependency-type: "direct"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "github_actions"
