// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI
{
    public static class GetEksClusterIdDataSource
    {
        public static Task<GetEksClusterIdDataSourceResult> InvokeAsync(GetEksClusterIdDataSourceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEksClusterIdDataSourceResult>("castai:aws:GetEksClusterIdDataSource", args ?? new GetEksClusterIdDataSourceArgs(), options.WithDefaults());

        public static Output<GetEksClusterIdDataSourceResult> Invoke(GetEksClusterIdDataSourceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEksClusterIdDataSourceResult>("castai:aws:GetEksClusterIdDataSource", args ?? new GetEksClusterIdDataSourceInvokeArgs(), options.WithDefaults());

        public static Output<GetEksClusterIdDataSourceResult> Invoke(GetEksClusterIdDataSourceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEksClusterIdDataSourceResult>("castai:aws:GetEksClusterIdDataSource", args ?? new GetEksClusterIdDataSourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEksClusterIdDataSourceArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId", required: true)]
        public string AccountId { get; set; } = null!;

        [Input("clusterName", required: true)]
        public string ClusterName { get; set; } = null!;

        [Input("region", required: true)]
        public string Region { get; set; } = null!;

        public GetEksClusterIdDataSourceArgs()
        {
        }
        public static new GetEksClusterIdDataSourceArgs Empty => new GetEksClusterIdDataSourceArgs();
    }

    public sealed class GetEksClusterIdDataSourceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("accountId", required: true)]
        public Input<string> AccountId { get; set; } = null!;

        [Input("clusterName", required: true)]
        public Input<string> ClusterName { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public GetEksClusterIdDataSourceInvokeArgs()
        {
        }
        public static new GetEksClusterIdDataSourceInvokeArgs Empty => new GetEksClusterIdDataSourceInvokeArgs();
    }


    [OutputType]
    public sealed class GetEksClusterIdDataSourceResult
    {
        public readonly string AccountId;
        public readonly string ClusterName;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Region;

        [OutputConstructor]
        private GetEksClusterIdDataSourceResult(
            string accountId,

            string clusterName,

            string id,

            string region)
        {
            AccountId = accountId;
            ClusterName = clusterName;
            Id = id;
            Region = region;
        }
    }
}
