// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI
{
    public static class GetRebalancingScheduleDataSource
    {
        public static Task<GetRebalancingScheduleDataSourceResult> InvokeAsync(GetRebalancingScheduleDataSourceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetRebalancingScheduleDataSourceResult>("castai:rebalancing:GetRebalancingScheduleDataSource", args ?? new GetRebalancingScheduleDataSourceArgs(), options.WithDefaults());

        public static Output<GetRebalancingScheduleDataSourceResult> Invoke(GetRebalancingScheduleDataSourceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetRebalancingScheduleDataSourceResult>("castai:rebalancing:GetRebalancingScheduleDataSource", args ?? new GetRebalancingScheduleDataSourceInvokeArgs(), options.WithDefaults());

        public static Output<GetRebalancingScheduleDataSourceResult> Invoke(GetRebalancingScheduleDataSourceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetRebalancingScheduleDataSourceResult>("castai:rebalancing:GetRebalancingScheduleDataSource", args ?? new GetRebalancingScheduleDataSourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetRebalancingScheduleDataSourceArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetRebalancingScheduleDataSourceArgs()
        {
        }
        public static new GetRebalancingScheduleDataSourceArgs Empty => new GetRebalancingScheduleDataSourceArgs();
    }

    public sealed class GetRebalancingScheduleDataSourceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetRebalancingScheduleDataSourceInvokeArgs()
        {
        }
        public static new GetRebalancingScheduleDataSourceInvokeArgs Empty => new GetRebalancingScheduleDataSourceInvokeArgs();
    }


    [OutputType]
    public sealed class GetRebalancingScheduleDataSourceResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Pulumi.CastAI.Rebalancing.Outputs.GetRebalancingScheduleDataSourceLaunchConfigurationResult> LaunchConfigurations;
        public readonly string Name;
        public readonly ImmutableArray<Pulumi.CastAI.Rebalancing.Outputs.GetRebalancingScheduleDataSourceScheduleResult> Schedules;
        public readonly ImmutableArray<Pulumi.CastAI.Rebalancing.Outputs.GetRebalancingScheduleDataSourceTriggerConditionResult> TriggerConditions;

        [OutputConstructor]
        private GetRebalancingScheduleDataSourceResult(
            string id,

            ImmutableArray<Pulumi.CastAI.Rebalancing.Outputs.GetRebalancingScheduleDataSourceLaunchConfigurationResult> launchConfigurations,

            string name,

            ImmutableArray<Pulumi.CastAI.Rebalancing.Outputs.GetRebalancingScheduleDataSourceScheduleResult> schedules,

            ImmutableArray<Pulumi.CastAI.Rebalancing.Outputs.GetRebalancingScheduleDataSourceTriggerConditionResult> triggerConditions)
        {
            Id = id;
            LaunchConfigurations = launchConfigurations;
            Name = name;
            Schedules = schedules;
            TriggerConditions = triggerConditions;
        }
    }
}
