// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI
{
    public static class GetWorkloadScalingPolicyOrderDataSource
    {
        public static Task<GetWorkloadScalingPolicyOrderDataSourceResult> InvokeAsync(GetWorkloadScalingPolicyOrderDataSourceArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetWorkloadScalingPolicyOrderDataSourceResult>("castai:workload:GetWorkloadScalingPolicyOrderDataSource", args ?? new GetWorkloadScalingPolicyOrderDataSourceArgs(), options.WithDefaults());

        public static Output<GetWorkloadScalingPolicyOrderDataSourceResult> Invoke(GetWorkloadScalingPolicyOrderDataSourceInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetWorkloadScalingPolicyOrderDataSourceResult>("castai:workload:GetWorkloadScalingPolicyOrderDataSource", args ?? new GetWorkloadScalingPolicyOrderDataSourceInvokeArgs(), options.WithDefaults());

        public static Output<GetWorkloadScalingPolicyOrderDataSourceResult> Invoke(GetWorkloadScalingPolicyOrderDataSourceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetWorkloadScalingPolicyOrderDataSourceResult>("castai:workload:GetWorkloadScalingPolicyOrderDataSource", args ?? new GetWorkloadScalingPolicyOrderDataSourceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetWorkloadScalingPolicyOrderDataSourceArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public string ClusterId { get; set; } = null!;

        public GetWorkloadScalingPolicyOrderDataSourceArgs()
        {
        }
        public static new GetWorkloadScalingPolicyOrderDataSourceArgs Empty => new GetWorkloadScalingPolicyOrderDataSourceArgs();
    }

    public sealed class GetWorkloadScalingPolicyOrderDataSourceInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        public GetWorkloadScalingPolicyOrderDataSourceInvokeArgs()
        {
        }
        public static new GetWorkloadScalingPolicyOrderDataSourceInvokeArgs Empty => new GetWorkloadScalingPolicyOrderDataSourceInvokeArgs();
    }


    [OutputType]
    public sealed class GetWorkloadScalingPolicyOrderDataSourceResult
    {
        public readonly string ClusterId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> PolicyIds;

        [OutputConstructor]
        private GetWorkloadScalingPolicyOrderDataSourceResult(
            string clusterId,

            string id,

            ImmutableArray<string> policyIds)
        {
            ClusterId = clusterId;
            Id = id;
            PolicyIds = policyIds;
        }
    }
}
