// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Iam.Outputs
{

    [OutputType]
    public sealed class EnterpriseRoleBindingSubjects
    {
        /// <summary>
        /// Group subjects.
        /// </summary>
        public readonly ImmutableArray<Outputs.EnterpriseRoleBindingSubjectsGroup> Groups;
        /// <summary>
        /// Service account subjects.
        /// </summary>
        public readonly ImmutableArray<Outputs.EnterpriseRoleBindingSubjectsServiceAccount> ServiceAccounts;
        /// <summary>
        /// User subjects.
        /// </summary>
        public readonly ImmutableArray<Outputs.EnterpriseRoleBindingSubjectsUser> Users;

        [OutputConstructor]
        private EnterpriseRoleBindingSubjects(
            ImmutableArray<Outputs.EnterpriseRoleBindingSubjectsGroup> groups,

            ImmutableArray<Outputs.EnterpriseRoleBindingSubjectsServiceAccount> serviceAccounts,

            ImmutableArray<Outputs.EnterpriseRoleBindingSubjectsUser> users)
        {
            Groups = groups;
            ServiceAccounts = serviceAccounts;
            Users = users;
        }
    }
}
