// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Iam.Outputs
{

    [OutputType]
    public sealed class EnterpriseRoleBindingScopes
    {
        /// <summary>
        /// Cluster scopes.
        /// </summary>
        public readonly ImmutableArray<Outputs.EnterpriseRoleBindingScopesCluster> Clusters;
        /// <summary>
        /// Organization scopes.
        /// </summary>
        public readonly ImmutableArray<Outputs.EnterpriseRoleBindingScopesOrganization> Organizations;

        [OutputConstructor]
        private EnterpriseRoleBindingScopes(
            ImmutableArray<Outputs.EnterpriseRoleBindingScopesCluster> clusters,

            ImmutableArray<Outputs.EnterpriseRoleBindingScopesOrganization> organizations)
        {
            Clusters = clusters;
            Organizations = organizations;
        }
    }
}
