// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Iam.Outputs
{

    [OutputType]
    public sealed class RoleBindingsScope
    {
        /// <summary>
        /// Scope of the role binding Supported values include: organization, cluster.
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// ID of the scope resource.
        /// </summary>
        public readonly string ResourceId;

        [OutputConstructor]
        private RoleBindingsScope(
            string kind,

            string resourceId)
        {
            Kind = kind;
            ResourceId = resourceId;
        }
    }
}
