// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Azure.Inputs
{

    public sealed class AksClusterHttpProxyConfigGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Address to use for proxying HTTP requests.
        /// </summary>
        [Input("httpProxy")]
        public Input<string>? HttpProxy { get; set; }

        /// <summary>
        /// Address to use for proxying HTTPS/TLS requests.
        /// </summary>
        [Input("httpsProxy")]
        public Input<string>? HttpsProxy { get; set; }

        [Input("noProxies")]
        private InputList<string>? _noProxies;

        /// <summary>
        /// List of destinations that should not go through proxy.
        /// </summary>
        public InputList<string> NoProxies
        {
            get => _noProxies ?? (_noProxies = new InputList<string>());
            set => _noProxies = value;
        }

        public AksClusterHttpProxyConfigGetArgs()
        {
        }
        public static new AksClusterHttpProxyConfigGetArgs Empty => new AksClusterHttpProxyConfigGetArgs();
    }
}
