// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Organization.Inputs
{

    public sealed class OrganizationGroupMemberMemberGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Kind of the member. Supported values include: user, service_account.
        /// </summary>
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        public OrganizationGroupMemberMemberGetArgs()
        {
        }
        public static new OrganizationGroupMemberMemberGetArgs Empty => new OrganizationGroupMemberMemberGetArgs();
    }
}
