// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package castai

import (
	"context"
	"reflect"

	"errors"
	"github.com/castai/pulumi-castai/sdk/go/castai/autoscaling"
	"github.com/castai/pulumi-castai/sdk/go/castai/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type EvictorAdvancedConfig struct {
	pulumi.CustomResourceState

	// CAST AI cluster id.
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// evictor advanced configuration to target specific node/pod
	EvictorAdvancedConfigs autoscaling.EvictorAdvancedConfigEvictorAdvancedConfigArrayOutput `pulumi:"evictorAdvancedConfigs"`
}

// NewEvictorAdvancedConfig registers a new resource with the given unique name, arguments, and options.
func NewEvictorAdvancedConfig(ctx *pulumi.Context,
	name string, args *EvictorAdvancedConfigArgs, opts ...pulumi.ResourceOption) (*EvictorAdvancedConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	if args.EvictorAdvancedConfigs == nil {
		return nil, errors.New("invalid value for required argument 'EvictorAdvancedConfigs'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EvictorAdvancedConfig
	err := ctx.RegisterResource("castai:autoscaling:EvictorAdvancedConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEvictorAdvancedConfig gets an existing EvictorAdvancedConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEvictorAdvancedConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EvictorAdvancedConfigState, opts ...pulumi.ResourceOption) (*EvictorAdvancedConfig, error) {
	var resource EvictorAdvancedConfig
	err := ctx.ReadResource("castai:autoscaling:EvictorAdvancedConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EvictorAdvancedConfig resources.
type evictorAdvancedConfigState struct {
	// CAST AI cluster id.
	ClusterId *string `pulumi:"clusterId"`
	// evictor advanced configuration to target specific node/pod
	EvictorAdvancedConfigs []autoscaling.EvictorAdvancedConfigEvictorAdvancedConfig `pulumi:"evictorAdvancedConfigs"`
}

type EvictorAdvancedConfigState struct {
	// CAST AI cluster id.
	ClusterId pulumi.StringPtrInput
	// evictor advanced configuration to target specific node/pod
	EvictorAdvancedConfigs autoscaling.EvictorAdvancedConfigEvictorAdvancedConfigArrayInput
}

func (EvictorAdvancedConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*evictorAdvancedConfigState)(nil)).Elem()
}

type evictorAdvancedConfigArgs struct {
	// CAST AI cluster id.
	ClusterId string `pulumi:"clusterId"`
	// evictor advanced configuration to target specific node/pod
	EvictorAdvancedConfigs []autoscaling.EvictorAdvancedConfigEvictorAdvancedConfig `pulumi:"evictorAdvancedConfigs"`
}

// The set of arguments for constructing a EvictorAdvancedConfig resource.
type EvictorAdvancedConfigArgs struct {
	// CAST AI cluster id.
	ClusterId pulumi.StringInput
	// evictor advanced configuration to target specific node/pod
	EvictorAdvancedConfigs autoscaling.EvictorAdvancedConfigEvictorAdvancedConfigArrayInput
}

func (EvictorAdvancedConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*evictorAdvancedConfigArgs)(nil)).Elem()
}

type EvictorAdvancedConfigInput interface {
	pulumi.Input

	ToEvictorAdvancedConfigOutput() EvictorAdvancedConfigOutput
	ToEvictorAdvancedConfigOutputWithContext(ctx context.Context) EvictorAdvancedConfigOutput
}

func (*EvictorAdvancedConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**EvictorAdvancedConfig)(nil)).Elem()
}

func (i *EvictorAdvancedConfig) ToEvictorAdvancedConfigOutput() EvictorAdvancedConfigOutput {
	return i.ToEvictorAdvancedConfigOutputWithContext(context.Background())
}

func (i *EvictorAdvancedConfig) ToEvictorAdvancedConfigOutputWithContext(ctx context.Context) EvictorAdvancedConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EvictorAdvancedConfigOutput)
}

// EvictorAdvancedConfigArrayInput is an input type that accepts EvictorAdvancedConfigArray and EvictorAdvancedConfigArrayOutput values.
// You can construct a concrete instance of `EvictorAdvancedConfigArrayInput` via:
//
//	EvictorAdvancedConfigArray{ EvictorAdvancedConfigArgs{...} }
type EvictorAdvancedConfigArrayInput interface {
	pulumi.Input

	ToEvictorAdvancedConfigArrayOutput() EvictorAdvancedConfigArrayOutput
	ToEvictorAdvancedConfigArrayOutputWithContext(context.Context) EvictorAdvancedConfigArrayOutput
}

type EvictorAdvancedConfigArray []EvictorAdvancedConfigInput

func (EvictorAdvancedConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EvictorAdvancedConfig)(nil)).Elem()
}

func (i EvictorAdvancedConfigArray) ToEvictorAdvancedConfigArrayOutput() EvictorAdvancedConfigArrayOutput {
	return i.ToEvictorAdvancedConfigArrayOutputWithContext(context.Background())
}

func (i EvictorAdvancedConfigArray) ToEvictorAdvancedConfigArrayOutputWithContext(ctx context.Context) EvictorAdvancedConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EvictorAdvancedConfigArrayOutput)
}

// EvictorAdvancedConfigMapInput is an input type that accepts EvictorAdvancedConfigMap and EvictorAdvancedConfigMapOutput values.
// You can construct a concrete instance of `EvictorAdvancedConfigMapInput` via:
//
//	EvictorAdvancedConfigMap{ "key": EvictorAdvancedConfigArgs{...} }
type EvictorAdvancedConfigMapInput interface {
	pulumi.Input

	ToEvictorAdvancedConfigMapOutput() EvictorAdvancedConfigMapOutput
	ToEvictorAdvancedConfigMapOutputWithContext(context.Context) EvictorAdvancedConfigMapOutput
}

type EvictorAdvancedConfigMap map[string]EvictorAdvancedConfigInput

func (EvictorAdvancedConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EvictorAdvancedConfig)(nil)).Elem()
}

func (i EvictorAdvancedConfigMap) ToEvictorAdvancedConfigMapOutput() EvictorAdvancedConfigMapOutput {
	return i.ToEvictorAdvancedConfigMapOutputWithContext(context.Background())
}

func (i EvictorAdvancedConfigMap) ToEvictorAdvancedConfigMapOutputWithContext(ctx context.Context) EvictorAdvancedConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EvictorAdvancedConfigMapOutput)
}

type EvictorAdvancedConfigOutput struct{ *pulumi.OutputState }

func (EvictorAdvancedConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EvictorAdvancedConfig)(nil)).Elem()
}

func (o EvictorAdvancedConfigOutput) ToEvictorAdvancedConfigOutput() EvictorAdvancedConfigOutput {
	return o
}

func (o EvictorAdvancedConfigOutput) ToEvictorAdvancedConfigOutputWithContext(ctx context.Context) EvictorAdvancedConfigOutput {
	return o
}

// CAST AI cluster id.
func (o EvictorAdvancedConfigOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *EvictorAdvancedConfig) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// evictor advanced configuration to target specific node/pod
func (o EvictorAdvancedConfigOutput) EvictorAdvancedConfigs() autoscaling.EvictorAdvancedConfigEvictorAdvancedConfigArrayOutput {
	return o.ApplyT(func(v *EvictorAdvancedConfig) autoscaling.EvictorAdvancedConfigEvictorAdvancedConfigArrayOutput {
		return v.EvictorAdvancedConfigs
	}).(autoscaling.EvictorAdvancedConfigEvictorAdvancedConfigArrayOutput)
}

type EvictorAdvancedConfigArrayOutput struct{ *pulumi.OutputState }

func (EvictorAdvancedConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EvictorAdvancedConfig)(nil)).Elem()
}

func (o EvictorAdvancedConfigArrayOutput) ToEvictorAdvancedConfigArrayOutput() EvictorAdvancedConfigArrayOutput {
	return o
}

func (o EvictorAdvancedConfigArrayOutput) ToEvictorAdvancedConfigArrayOutputWithContext(ctx context.Context) EvictorAdvancedConfigArrayOutput {
	return o
}

func (o EvictorAdvancedConfigArrayOutput) Index(i pulumi.IntInput) EvictorAdvancedConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EvictorAdvancedConfig {
		return vs[0].([]*EvictorAdvancedConfig)[vs[1].(int)]
	}).(EvictorAdvancedConfigOutput)
}

type EvictorAdvancedConfigMapOutput struct{ *pulumi.OutputState }

func (EvictorAdvancedConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EvictorAdvancedConfig)(nil)).Elem()
}

func (o EvictorAdvancedConfigMapOutput) ToEvictorAdvancedConfigMapOutput() EvictorAdvancedConfigMapOutput {
	return o
}

func (o EvictorAdvancedConfigMapOutput) ToEvictorAdvancedConfigMapOutputWithContext(ctx context.Context) EvictorAdvancedConfigMapOutput {
	return o
}

func (o EvictorAdvancedConfigMapOutput) MapIndex(k pulumi.StringInput) EvictorAdvancedConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EvictorAdvancedConfig {
		return vs[0].(map[string]*EvictorAdvancedConfig)[vs[1].(string)]
	}).(EvictorAdvancedConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EvictorAdvancedConfigInput)(nil)).Elem(), &EvictorAdvancedConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*EvictorAdvancedConfigArrayInput)(nil)).Elem(), EvictorAdvancedConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EvictorAdvancedConfigMapInput)(nil)).Elem(), EvictorAdvancedConfigMap{})
	pulumi.RegisterOutputType(EvictorAdvancedConfigOutput{})
	pulumi.RegisterOutputType(EvictorAdvancedConfigArrayOutput{})
	pulumi.RegisterOutputType(EvictorAdvancedConfigMapOutput{})
}
