// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package castai

import (
	"context"
	"reflect"

	"github.com/cast-ai/pulumi-castai/sdk/go/castai/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetEksSettingsDataSource(ctx *pulumi.Context, args *GetEksSettingsDataSourceArgs, opts ...pulumi.InvokeOption) (*GetEksSettingsDataSourceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetEksSettingsDataSourceResult
	err := ctx.Invoke("castai:aws:GetEksSettingsDataSource", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetEksSettingsDataSource.
type GetEksSettingsDataSourceArgs struct {
	AccountId string `pulumi:"accountId"`
	Cluster   string `pulumi:"cluster"`
	Region    string `pulumi:"region"`
	Vpc       string `pulumi:"vpc"`
}

// A collection of values returned by GetEksSettingsDataSource.
type GetEksSettingsDataSourceResult struct {
	AccountId          string   `pulumi:"accountId"`
	Cluster            string   `pulumi:"cluster"`
	IamManagedPolicies []string `pulumi:"iamManagedPolicies"`
	IamPolicyJson      string   `pulumi:"iamPolicyJson"`
	IamUserPolicyJson  string   `pulumi:"iamUserPolicyJson"`
	// The provider-assigned unique ID for this managed resource.
	Id                      string   `pulumi:"id"`
	InstanceProfilePolicies []string `pulumi:"instanceProfilePolicies"`
	Region                  string   `pulumi:"region"`
	Vpc                     string   `pulumi:"vpc"`
}

func GetEksSettingsDataSourceOutput(ctx *pulumi.Context, args GetEksSettingsDataSourceOutputArgs, opts ...pulumi.InvokeOption) GetEksSettingsDataSourceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetEksSettingsDataSourceResultOutput, error) {
			args := v.(GetEksSettingsDataSourceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("castai:aws:GetEksSettingsDataSource", args, GetEksSettingsDataSourceResultOutput{}, options).(GetEksSettingsDataSourceResultOutput), nil
		}).(GetEksSettingsDataSourceResultOutput)
}

// A collection of arguments for invoking GetEksSettingsDataSource.
type GetEksSettingsDataSourceOutputArgs struct {
	AccountId pulumi.StringInput `pulumi:"accountId"`
	Cluster   pulumi.StringInput `pulumi:"cluster"`
	Region    pulumi.StringInput `pulumi:"region"`
	Vpc       pulumi.StringInput `pulumi:"vpc"`
}

func (GetEksSettingsDataSourceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEksSettingsDataSourceArgs)(nil)).Elem()
}

// A collection of values returned by GetEksSettingsDataSource.
type GetEksSettingsDataSourceResultOutput struct{ *pulumi.OutputState }

func (GetEksSettingsDataSourceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetEksSettingsDataSourceResult)(nil)).Elem()
}

func (o GetEksSettingsDataSourceResultOutput) ToGetEksSettingsDataSourceResultOutput() GetEksSettingsDataSourceResultOutput {
	return o
}

func (o GetEksSettingsDataSourceResultOutput) ToGetEksSettingsDataSourceResultOutputWithContext(ctx context.Context) GetEksSettingsDataSourceResultOutput {
	return o
}

func (o GetEksSettingsDataSourceResultOutput) AccountId() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.AccountId }).(pulumi.StringOutput)
}

func (o GetEksSettingsDataSourceResultOutput) Cluster() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.Cluster }).(pulumi.StringOutput)
}

func (o GetEksSettingsDataSourceResultOutput) IamManagedPolicies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) []string { return v.IamManagedPolicies }).(pulumi.StringArrayOutput)
}

func (o GetEksSettingsDataSourceResultOutput) IamPolicyJson() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.IamPolicyJson }).(pulumi.StringOutput)
}

func (o GetEksSettingsDataSourceResultOutput) IamUserPolicyJson() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.IamUserPolicyJson }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetEksSettingsDataSourceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetEksSettingsDataSourceResultOutput) InstanceProfilePolicies() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) []string { return v.InstanceProfilePolicies }).(pulumi.StringArrayOutput)
}

func (o GetEksSettingsDataSourceResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetEksSettingsDataSourceResultOutput) Vpc() pulumi.StringOutput {
	return o.ApplyT(func(v GetEksSettingsDataSourceResult) string { return v.Vpc }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetEksSettingsDataSourceResultOutput{})
}
