// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package castai

import (
	"context"
	"reflect"

	"github.com/castai/pulumi-castai/sdk/go/castai/internal"
	"github.com/castai/pulumi-castai/sdk/go/castai/rebalancing"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetHibernationScheduleDataSource(ctx *pulumi.Context, args *GetHibernationScheduleDataSourceArgs, opts ...pulumi.InvokeOption) (*GetHibernationScheduleDataSourceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetHibernationScheduleDataSourceResult
	err := ctx.Invoke("castai:rebalancing:GetHibernationScheduleDataSource", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking GetHibernationScheduleDataSource.
type GetHibernationScheduleDataSourceArgs struct {
	ClusterAssignments []rebalancing.GetHibernationScheduleDataSourceClusterAssignment `pulumi:"clusterAssignments"`
	Name               string                                                          `pulumi:"name"`
	OrganizationId     *string                                                         `pulumi:"organizationId"`
}

// A collection of values returned by GetHibernationScheduleDataSource.
type GetHibernationScheduleDataSourceResult struct {
	ClusterAssignments []rebalancing.GetHibernationScheduleDataSourceClusterAssignment `pulumi:"clusterAssignments"`
	Enabled            bool                                                            `pulumi:"enabled"`
	// The provider-assigned unique ID for this managed resource.
	Id             string                                                     `pulumi:"id"`
	Name           string                                                     `pulumi:"name"`
	OrganizationId *string                                                    `pulumi:"organizationId"`
	PauseConfigs   []rebalancing.GetHibernationScheduleDataSourcePauseConfig  `pulumi:"pauseConfigs"`
	ResumeConfigs  []rebalancing.GetHibernationScheduleDataSourceResumeConfig `pulumi:"resumeConfigs"`
}

func GetHibernationScheduleDataSourceOutput(ctx *pulumi.Context, args GetHibernationScheduleDataSourceOutputArgs, opts ...pulumi.InvokeOption) GetHibernationScheduleDataSourceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetHibernationScheduleDataSourceResultOutput, error) {
			args := v.(GetHibernationScheduleDataSourceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("castai:rebalancing:GetHibernationScheduleDataSource", args, GetHibernationScheduleDataSourceResultOutput{}, options).(GetHibernationScheduleDataSourceResultOutput), nil
		}).(GetHibernationScheduleDataSourceResultOutput)
}

// A collection of arguments for invoking GetHibernationScheduleDataSource.
type GetHibernationScheduleDataSourceOutputArgs struct {
	ClusterAssignments rebalancing.GetHibernationScheduleDataSourceClusterAssignmentArrayInput `pulumi:"clusterAssignments"`
	Name               pulumi.StringInput                                                      `pulumi:"name"`
	OrganizationId     pulumi.StringPtrInput                                                   `pulumi:"organizationId"`
}

func (GetHibernationScheduleDataSourceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHibernationScheduleDataSourceArgs)(nil)).Elem()
}

// A collection of values returned by GetHibernationScheduleDataSource.
type GetHibernationScheduleDataSourceResultOutput struct{ *pulumi.OutputState }

func (GetHibernationScheduleDataSourceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetHibernationScheduleDataSourceResult)(nil)).Elem()
}

func (o GetHibernationScheduleDataSourceResultOutput) ToGetHibernationScheduleDataSourceResultOutput() GetHibernationScheduleDataSourceResultOutput {
	return o
}

func (o GetHibernationScheduleDataSourceResultOutput) ToGetHibernationScheduleDataSourceResultOutputWithContext(ctx context.Context) GetHibernationScheduleDataSourceResultOutput {
	return o
}

func (o GetHibernationScheduleDataSourceResultOutput) ClusterAssignments() rebalancing.GetHibernationScheduleDataSourceClusterAssignmentArrayOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) []rebalancing.GetHibernationScheduleDataSourceClusterAssignment {
		return v.ClusterAssignments
	}).(rebalancing.GetHibernationScheduleDataSourceClusterAssignmentArrayOutput)
}

func (o GetHibernationScheduleDataSourceResultOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) bool { return v.Enabled }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetHibernationScheduleDataSourceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetHibernationScheduleDataSourceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetHibernationScheduleDataSourceResultOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) *string { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

func (o GetHibernationScheduleDataSourceResultOutput) PauseConfigs() rebalancing.GetHibernationScheduleDataSourcePauseConfigArrayOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) []rebalancing.GetHibernationScheduleDataSourcePauseConfig {
		return v.PauseConfigs
	}).(rebalancing.GetHibernationScheduleDataSourcePauseConfigArrayOutput)
}

func (o GetHibernationScheduleDataSourceResultOutput) ResumeConfigs() rebalancing.GetHibernationScheduleDataSourceResumeConfigArrayOutput {
	return o.ApplyT(func(v GetHibernationScheduleDataSourceResult) []rebalancing.GetHibernationScheduleDataSourceResumeConfig {
		return v.ResumeConfigs
	}).(rebalancing.GetHibernationScheduleDataSourceResumeConfigArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetHibernationScheduleDataSourceResultOutput{})
}
