// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package castai

import (
	"context"
	"reflect"

	"errors"
	"github.com/castai/pulumi-castai/sdk/go/castai/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ServiceAccountKey struct {
	pulumi.CustomResourceState

	// Whether the service account key is active. Defaults to true.
	Active pulumi.BoolPtrOutput `pulumi:"active"`
	// The expiration time of the service account key in RFC3339 format. Defaults to an empty string.
	ExpiresAt pulumi.StringPtrOutput `pulumi:"expiresAt"`
	// Last time the service account key was used.
	LastUsedAt pulumi.StringOutput `pulumi:"lastUsedAt"`
	// Name of the service account key.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the organization.
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// Prefix of the service account key.
	Prefix pulumi.StringOutput `pulumi:"prefix"`
	// ID of the service account.
	ServiceAccountId pulumi.StringOutput `pulumi:"serviceAccountId"`
	// The token of the service account key used for authentication.
	Token pulumi.StringOutput `pulumi:"token"`
}

// NewServiceAccountKey registers a new resource with the given unique name, arguments, and options.
func NewServiceAccountKey(ctx *pulumi.Context,
	name string, args *ServiceAccountKeyArgs, opts ...pulumi.ResourceOption) (*ServiceAccountKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	if args.ServiceAccountId == nil {
		return nil, errors.New("invalid value for required argument 'ServiceAccountId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServiceAccountKey
	err := ctx.RegisterResource("castai:organization:ServiceAccountKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServiceAccountKey gets an existing ServiceAccountKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServiceAccountKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServiceAccountKeyState, opts ...pulumi.ResourceOption) (*ServiceAccountKey, error) {
	var resource ServiceAccountKey
	err := ctx.ReadResource("castai:organization:ServiceAccountKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServiceAccountKey resources.
type serviceAccountKeyState struct {
	// Whether the service account key is active. Defaults to true.
	Active *bool `pulumi:"active"`
	// The expiration time of the service account key in RFC3339 format. Defaults to an empty string.
	ExpiresAt *string `pulumi:"expiresAt"`
	// Last time the service account key was used.
	LastUsedAt *string `pulumi:"lastUsedAt"`
	// Name of the service account key.
	Name *string `pulumi:"name"`
	// ID of the organization.
	OrganizationId *string `pulumi:"organizationId"`
	// Prefix of the service account key.
	Prefix *string `pulumi:"prefix"`
	// ID of the service account.
	ServiceAccountId *string `pulumi:"serviceAccountId"`
	// The token of the service account key used for authentication.
	Token *string `pulumi:"token"`
}

type ServiceAccountKeyState struct {
	// Whether the service account key is active. Defaults to true.
	Active pulumi.BoolPtrInput
	// The expiration time of the service account key in RFC3339 format. Defaults to an empty string.
	ExpiresAt pulumi.StringPtrInput
	// Last time the service account key was used.
	LastUsedAt pulumi.StringPtrInput
	// Name of the service account key.
	Name pulumi.StringPtrInput
	// ID of the organization.
	OrganizationId pulumi.StringPtrInput
	// Prefix of the service account key.
	Prefix pulumi.StringPtrInput
	// ID of the service account.
	ServiceAccountId pulumi.StringPtrInput
	// The token of the service account key used for authentication.
	Token pulumi.StringPtrInput
}

func (ServiceAccountKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceAccountKeyState)(nil)).Elem()
}

type serviceAccountKeyArgs struct {
	// Whether the service account key is active. Defaults to true.
	Active *bool `pulumi:"active"`
	// The expiration time of the service account key in RFC3339 format. Defaults to an empty string.
	ExpiresAt *string `pulumi:"expiresAt"`
	// Name of the service account key.
	Name *string `pulumi:"name"`
	// ID of the organization.
	OrganizationId string `pulumi:"organizationId"`
	// ID of the service account.
	ServiceAccountId string `pulumi:"serviceAccountId"`
}

// The set of arguments for constructing a ServiceAccountKey resource.
type ServiceAccountKeyArgs struct {
	// Whether the service account key is active. Defaults to true.
	Active pulumi.BoolPtrInput
	// The expiration time of the service account key in RFC3339 format. Defaults to an empty string.
	ExpiresAt pulumi.StringPtrInput
	// Name of the service account key.
	Name pulumi.StringPtrInput
	// ID of the organization.
	OrganizationId pulumi.StringInput
	// ID of the service account.
	ServiceAccountId pulumi.StringInput
}

func (ServiceAccountKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serviceAccountKeyArgs)(nil)).Elem()
}

type ServiceAccountKeyInput interface {
	pulumi.Input

	ToServiceAccountKeyOutput() ServiceAccountKeyOutput
	ToServiceAccountKeyOutputWithContext(ctx context.Context) ServiceAccountKeyOutput
}

func (*ServiceAccountKey) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceAccountKey)(nil)).Elem()
}

func (i *ServiceAccountKey) ToServiceAccountKeyOutput() ServiceAccountKeyOutput {
	return i.ToServiceAccountKeyOutputWithContext(context.Background())
}

func (i *ServiceAccountKey) ToServiceAccountKeyOutputWithContext(ctx context.Context) ServiceAccountKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceAccountKeyOutput)
}

// ServiceAccountKeyArrayInput is an input type that accepts ServiceAccountKeyArray and ServiceAccountKeyArrayOutput values.
// You can construct a concrete instance of `ServiceAccountKeyArrayInput` via:
//
//	ServiceAccountKeyArray{ ServiceAccountKeyArgs{...} }
type ServiceAccountKeyArrayInput interface {
	pulumi.Input

	ToServiceAccountKeyArrayOutput() ServiceAccountKeyArrayOutput
	ToServiceAccountKeyArrayOutputWithContext(context.Context) ServiceAccountKeyArrayOutput
}

type ServiceAccountKeyArray []ServiceAccountKeyInput

func (ServiceAccountKeyArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServiceAccountKey)(nil)).Elem()
}

func (i ServiceAccountKeyArray) ToServiceAccountKeyArrayOutput() ServiceAccountKeyArrayOutput {
	return i.ToServiceAccountKeyArrayOutputWithContext(context.Background())
}

func (i ServiceAccountKeyArray) ToServiceAccountKeyArrayOutputWithContext(ctx context.Context) ServiceAccountKeyArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceAccountKeyArrayOutput)
}

// ServiceAccountKeyMapInput is an input type that accepts ServiceAccountKeyMap and ServiceAccountKeyMapOutput values.
// You can construct a concrete instance of `ServiceAccountKeyMapInput` via:
//
//	ServiceAccountKeyMap{ "key": ServiceAccountKeyArgs{...} }
type ServiceAccountKeyMapInput interface {
	pulumi.Input

	ToServiceAccountKeyMapOutput() ServiceAccountKeyMapOutput
	ToServiceAccountKeyMapOutputWithContext(context.Context) ServiceAccountKeyMapOutput
}

type ServiceAccountKeyMap map[string]ServiceAccountKeyInput

func (ServiceAccountKeyMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServiceAccountKey)(nil)).Elem()
}

func (i ServiceAccountKeyMap) ToServiceAccountKeyMapOutput() ServiceAccountKeyMapOutput {
	return i.ToServiceAccountKeyMapOutputWithContext(context.Background())
}

func (i ServiceAccountKeyMap) ToServiceAccountKeyMapOutputWithContext(ctx context.Context) ServiceAccountKeyMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServiceAccountKeyMapOutput)
}

type ServiceAccountKeyOutput struct{ *pulumi.OutputState }

func (ServiceAccountKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServiceAccountKey)(nil)).Elem()
}

func (o ServiceAccountKeyOutput) ToServiceAccountKeyOutput() ServiceAccountKeyOutput {
	return o
}

func (o ServiceAccountKeyOutput) ToServiceAccountKeyOutputWithContext(ctx context.Context) ServiceAccountKeyOutput {
	return o
}

// Whether the service account key is active. Defaults to true.
func (o ServiceAccountKeyOutput) Active() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.BoolPtrOutput { return v.Active }).(pulumi.BoolPtrOutput)
}

// The expiration time of the service account key in RFC3339 format. Defaults to an empty string.
func (o ServiceAccountKeyOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringPtrOutput { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// Last time the service account key was used.
func (o ServiceAccountKeyOutput) LastUsedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringOutput { return v.LastUsedAt }).(pulumi.StringOutput)
}

// Name of the service account key.
func (o ServiceAccountKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the organization.
func (o ServiceAccountKeyOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// Prefix of the service account key.
func (o ServiceAccountKeyOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringOutput { return v.Prefix }).(pulumi.StringOutput)
}

// ID of the service account.
func (o ServiceAccountKeyOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringOutput { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// The token of the service account key used for authentication.
func (o ServiceAccountKeyOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *ServiceAccountKey) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

type ServiceAccountKeyArrayOutput struct{ *pulumi.OutputState }

func (ServiceAccountKeyArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServiceAccountKey)(nil)).Elem()
}

func (o ServiceAccountKeyArrayOutput) ToServiceAccountKeyArrayOutput() ServiceAccountKeyArrayOutput {
	return o
}

func (o ServiceAccountKeyArrayOutput) ToServiceAccountKeyArrayOutputWithContext(ctx context.Context) ServiceAccountKeyArrayOutput {
	return o
}

func (o ServiceAccountKeyArrayOutput) Index(i pulumi.IntInput) ServiceAccountKeyOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServiceAccountKey {
		return vs[0].([]*ServiceAccountKey)[vs[1].(int)]
	}).(ServiceAccountKeyOutput)
}

type ServiceAccountKeyMapOutput struct{ *pulumi.OutputState }

func (ServiceAccountKeyMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServiceAccountKey)(nil)).Elem()
}

func (o ServiceAccountKeyMapOutput) ToServiceAccountKeyMapOutput() ServiceAccountKeyMapOutput {
	return o
}

func (o ServiceAccountKeyMapOutput) ToServiceAccountKeyMapOutputWithContext(ctx context.Context) ServiceAccountKeyMapOutput {
	return o
}

func (o ServiceAccountKeyMapOutput) MapIndex(k pulumi.StringInput) ServiceAccountKeyOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServiceAccountKey {
		return vs[0].(map[string]*ServiceAccountKey)[vs[1].(string)]
	}).(ServiceAccountKeyOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceAccountKeyInput)(nil)).Elem(), &ServiceAccountKey{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceAccountKeyArrayInput)(nil)).Elem(), ServiceAccountKeyArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServiceAccountKeyMapInput)(nil)).Elem(), ServiceAccountKeyMap{})
	pulumi.RegisterOutputType(ServiceAccountKeyOutput{})
	pulumi.RegisterOutputType(ServiceAccountKeyArrayOutput{})
	pulumi.RegisterOutputType(ServiceAccountKeyMapOutput{})
}
