// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Workload.Inputs
{

    public sealed class WorkloadScalingPolicyAssignmentRuleRuleWorkloadArgs : global::Pulumi.ResourceArgs
    {
        [Input("gvks")]
        private InputList<string>? _gvks;

        /// <summary>
        /// Group, version, and kind for Kubernetes resources. Format: kind[.version][.group].
        /// It can be either:
        ///  - only kind, e.g. "Deployment"
        ///  - group and kind: e.g."Deployment.apps"
        ///  - group, version and kind: e.g."Deployment.v1.apps"
        /// </summary>
        public InputList<string> Gvks
        {
            get => _gvks ?? (_gvks = new InputList<string>());
            set => _gvks = value;
        }

        [Input("labelsExpressions")]
        private InputList<Inputs.WorkloadScalingPolicyAssignmentRuleRuleWorkloadLabelsExpressionArgs>? _labelsExpressions;

        /// <summary>
        /// Defines matching by label selector requirements.
        /// </summary>
        public InputList<Inputs.WorkloadScalingPolicyAssignmentRuleRuleWorkloadLabelsExpressionArgs> LabelsExpressions
        {
            get => _labelsExpressions ?? (_labelsExpressions = new InputList<Inputs.WorkloadScalingPolicyAssignmentRuleRuleWorkloadLabelsExpressionArgs>());
            set => _labelsExpressions = value;
        }

        public WorkloadScalingPolicyAssignmentRuleRuleWorkloadArgs()
        {
        }
        public static new WorkloadScalingPolicyAssignmentRuleRuleWorkloadArgs Empty => new WorkloadScalingPolicyAssignmentRuleRuleWorkloadArgs();
    }
}
