// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Workload.Inputs
{

    public sealed class WorkloadScalingPolicyPredictiveScalingGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Defines predictive scaling resource configuration.
        /// </summary>
        [Input("cpu")]
        public Input<Inputs.WorkloadScalingPolicyPredictiveScalingCpuGetArgs>? Cpu { get; set; }

        public WorkloadScalingPolicyPredictiveScalingGetArgs()
        {
        }
        public static new WorkloadScalingPolicyPredictiveScalingGetArgs Empty => new WorkloadScalingPolicyPredictiveScalingGetArgs();
    }
}
