// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Workload.Inputs
{

    public sealed class WorkloadScalingPolicyCpuLimitArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Multiplier used to calculate the resource limit. It must be defined for the MULTIPLIER strategy.
        /// </summary>
        [Input("multiplier")]
        public Input<double>? Multiplier { get; set; }

        /// <summary>
        /// Defines limit strategy type.
        /// 	- NO_LIMIT - removes the resource limit even if it was specified in the workload spec.
        /// 	- KEEP_LIMITS - keep existing resource limits. While limits provide stability predictability, they may restrict workloads that need to temporarily burst beyond their allocation.
        /// 	- MULTIPLIER - used to calculate the resource limit. The final value is determined by multiplying the resource request by the specified factor.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public WorkloadScalingPolicyCpuLimitArgs()
        {
        }
        public static new WorkloadScalingPolicyCpuLimitArgs Empty => new WorkloadScalingPolicyCpuLimitArgs();
    }
}
