// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Workload.Inputs
{

    public sealed class WorkloadScalingPolicyAssignmentRuleRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows assigning a scaling policy based on the workload's namespace.
        /// </summary>
        [Input("namespace")]
        public Input<Inputs.WorkloadScalingPolicyAssignmentRuleRuleNamespaceArgs>? Namespace { get; set; }

        /// <summary>
        /// Allows assigning a scaling policy based on the workload's metadata.
        /// </summary>
        [Input("workload")]
        public Input<Inputs.WorkloadScalingPolicyAssignmentRuleRuleWorkloadArgs>? Workload { get; set; }

        public WorkloadScalingPolicyAssignmentRuleRuleArgs()
        {
        }
        public static new WorkloadScalingPolicyAssignmentRuleRuleArgs Empty => new WorkloadScalingPolicyAssignmentRuleRuleArgs();
    }
}
