// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("castai");

/**
 * The token used to connect to CAST AI API.
 */
export declare const apiToken: string | undefined;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken") ?? utilities.getEnv("CASTAI_API_TOKEN");
    },
    enumerable: true,
});

/**
 * CAST.AI API url.
 */
export declare const apiUrl: string;
Object.defineProperty(exports, "apiUrl", {
    get() {
        return __config.get("apiUrl") ?? (utilities.getEnv("CASTAI_API_URL") || "https://api.cast.ai");
    },
    enumerable: true,
});

