// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Outputs
{

    [OutputType]
    public sealed class ClusterAutoscalerPoliciesUnschedulablePods
    {
        public readonly bool? Enabled;
        public readonly Outputs.ClusterAutoscalerPoliciesUnschedulablePodsHeadroom? Headroom;
        public readonly Outputs.ClusterAutoscalerPoliciesUnschedulablePodsNodeConstraints? NodeConstraints;

        [OutputConstructor]
        private ClusterAutoscalerPoliciesUnschedulablePods(
            bool? enabled,

            Outputs.ClusterAutoscalerPoliciesUnschedulablePodsHeadroom? headroom,

            Outputs.ClusterAutoscalerPoliciesUnschedulablePodsNodeConstraints? nodeConstraints)
        {
            Enabled = enabled;
            Headroom = headroom;
            NodeConstraints = nodeConstraints;
        }
    }
}
