// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Outputs
{

    [OutputType]
    public sealed class ReservationsReservation
    {
        /// <summary>
        /// amount of reserved instances
        /// </summary>
        public readonly string Count;
        /// <summary>
        /// end date of reservation
        /// </summary>
        public readonly string? EndDate;
        /// <summary>
        /// reserved instance type
        /// </summary>
        public readonly string InstanceType;
        /// <summary>
        /// unique reservation name in region for specific instance type
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// reservation price
        /// </summary>
        public readonly string Price;
        /// <summary>
        /// reservation cloud provider (gcp, aws, azure)
        /// </summary>
        public readonly string Provider;
        /// <summary>
        /// reservation region
        /// </summary>
        public readonly string Region;
        /// <summary>
        /// start date of reservation
        /// </summary>
        public readonly string StartDate;
        /// <summary>
        /// reservation zone id
        /// </summary>
        public readonly string? ZoneId;
        /// <summary>
        /// reservation zone name
        /// </summary>
        public readonly string? ZoneName;

        [OutputConstructor]
        private ReservationsReservation(
            string count,

            string? endDate,

            string instanceType,

            string name,

            string price,

            string provider,

            string region,

            string startDate,

            string? zoneId,

            string? zoneName)
        {
            Count = count;
            EndDate = endDate;
            InstanceType = instanceType;
            Name = name;
            Price = price;
            Provider = provider;
            Region = region;
            StartDate = startDate;
            ZoneId = zoneId;
            ZoneName = zoneName;
        }
    }
}
