// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Rebalancing.Outputs
{

    [OutputType]
    public sealed class HibernationScheduleResumeConfigJobConfigNodeConfigVolume
    {
        public readonly ImmutableArray<Outputs.HibernationScheduleResumeConfigJobConfigNodeConfigVolumeRaidConfig> RaidConfigs;
        /// <summary>
        /// Volume size in GiB.
        /// </summary>
        public readonly int? SizeGib;

        [OutputConstructor]
        private HibernationScheduleResumeConfigJobConfigNodeConfigVolume(
            ImmutableArray<Outputs.HibernationScheduleResumeConfigJobConfigNodeConfigVolumeRaidConfig> raidConfigs,

            int? sizeGib)
        {
            RaidConfigs = raidConfigs;
            SizeGib = sizeGib;
        }
    }
}
