// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Rebalancing.Outputs
{

    [OutputType]
    public sealed class HibernationScheduleResumeConfigJobConfigNodeConfigGpuConfig
    {
        /// <summary>
        /// Number of GPUs.
        /// </summary>
        public readonly int Count;
        /// <summary>
        /// GPU type.
        /// </summary>
        public readonly string? Type;

        [OutputConstructor]
        private HibernationScheduleResumeConfigJobConfigNodeConfigGpuConfig(
            int count,

            string? type)
        {
            Count = count;
            Type = type;
        }
    }
}
