// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Rebalancing.Outputs
{

    [OutputType]
    public sealed class HibernationScheduleClusterAssignmentsAssignment
    {
        /// <summary>
        /// ID of the cluster.
        /// </summary>
        public readonly string ClusterId;

        [OutputConstructor]
        private HibernationScheduleClusterAssignmentsAssignment(string clusterId)
        {
            ClusterId = clusterId;
        }
    }
}
