// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Autoscaling.Inputs
{

    public sealed class AutoscalerAutoscalerSettingsUnschedulablePodsHeadroomGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// defines percentage of additional CPU capacity to be added.
        /// </summary>
        [Input("cpuPercentage")]
        public Input<int>? CpuPercentage { get; set; }

        /// <summary>
        /// enable/disable headroom policy.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// defines percentage of additional memory capacity to be added.
        /// </summary>
        [Input("memoryPercentage")]
        public Input<int>? MemoryPercentage { get; set; }

        public AutoscalerAutoscalerSettingsUnschedulablePodsHeadroomGetArgs()
        {
        }
        public static new AutoscalerAutoscalerSettingsUnschedulablePodsHeadroomGetArgs Empty => new AutoscalerAutoscalerSettingsUnschedulablePodsHeadroomGetArgs();
    }
}
