// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Autoscaling.Inputs
{

    public sealed class AutoscalerAutoscalerSettingsSpotInstancesSpotBackupsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// enable/disable spot backups policy.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// defines interval on how often spot backups restore to real spot should occur.
        /// </summary>
        [Input("spotBackupRestoreRateSeconds")]
        public Input<int>? SpotBackupRestoreRateSeconds { get; set; }

        public AutoscalerAutoscalerSettingsSpotInstancesSpotBackupsGetArgs()
        {
        }
        public static new AutoscalerAutoscalerSettingsSpotInstancesSpotBackupsGetArgs Empty => new AutoscalerAutoscalerSettingsSpotInstancesSpotBackupsGetArgs();
    }
}
