// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Organization.Outputs
{

    [OutputType]
    public sealed class EnterpriseGroupMemberMember
    {
        /// <summary>
        /// Member UUID.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Kind of the member. Supported values: user, service_account.
        /// </summary>
        public readonly string Kind;

        [OutputConstructor]
        private EnterpriseGroupMemberMember(
            string id,

            string kind)
        {
            Id = id;
            Kind = kind;
        }
    }
}
