// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Iam.Inputs
{

    public sealed class EnterpriseRoleBindingSubjectsArgs : global::Pulumi.ResourceArgs
    {
        [Input("groups")]
        private InputList<Inputs.EnterpriseRoleBindingSubjectsGroupArgs>? _groups;

        /// <summary>
        /// Group subjects.
        /// </summary>
        public InputList<Inputs.EnterpriseRoleBindingSubjectsGroupArgs> Groups
        {
            get => _groups ?? (_groups = new InputList<Inputs.EnterpriseRoleBindingSubjectsGroupArgs>());
            set => _groups = value;
        }

        [Input("serviceAccounts")]
        private InputList<Inputs.EnterpriseRoleBindingSubjectsServiceAccountArgs>? _serviceAccounts;

        /// <summary>
        /// Service account subjects.
        /// </summary>
        public InputList<Inputs.EnterpriseRoleBindingSubjectsServiceAccountArgs> ServiceAccounts
        {
            get => _serviceAccounts ?? (_serviceAccounts = new InputList<Inputs.EnterpriseRoleBindingSubjectsServiceAccountArgs>());
            set => _serviceAccounts = value;
        }

        [Input("users")]
        private InputList<Inputs.EnterpriseRoleBindingSubjectsUserArgs>? _users;

        /// <summary>
        /// User subjects.
        /// </summary>
        public InputList<Inputs.EnterpriseRoleBindingSubjectsUserArgs> Users
        {
            get => _users ?? (_users = new InputList<Inputs.EnterpriseRoleBindingSubjectsUserArgs>());
            set => _users = value;
        }

        public EnterpriseRoleBindingSubjectsArgs()
        {
        }
        public static new EnterpriseRoleBindingSubjectsArgs Empty => new EnterpriseRoleBindingSubjectsArgs();
    }
}
