// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Iam.Inputs
{

    public sealed class EnterpriseRoleBindingSubjectsGroupArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group ID.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public EnterpriseRoleBindingSubjectsGroupArgs()
        {
        }
        public static new EnterpriseRoleBindingSubjectsGroupArgs Empty => new EnterpriseRoleBindingSubjectsGroupArgs();
    }
}
