// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Azure.Outputs
{

    [OutputType]
    public sealed class AksClusterHttpProxyConfig
    {
        /// <summary>
        /// Address to use for proxying HTTP requests.
        /// </summary>
        public readonly string? HttpProxy;
        /// <summary>
        /// Address to use for proxying HTTPS/TLS requests.
        /// </summary>
        public readonly string? HttpsProxy;
        /// <summary>
        /// List of destinations that should not go through proxy.
        /// </summary>
        public readonly ImmutableArray<string> NoProxies;

        [OutputConstructor]
        private AksClusterHttpProxyConfig(
            string? httpProxy,

            string? httpsProxy,

            ImmutableArray<string> noProxies)
        {
            HttpProxy = httpProxy;
            HttpsProxy = httpsProxy;
            NoProxies = noProxies;
        }
    }
}
