// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Inputs
{

    public sealed class ClusterAutoscalerPoliciesUnschedulablePodsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        [Input("headroom")]
        public Input<Inputs.ClusterAutoscalerPoliciesUnschedulablePodsHeadroomGetArgs>? Headroom { get; set; }

        [Input("nodeConstraints")]
        public Input<Inputs.ClusterAutoscalerPoliciesUnschedulablePodsNodeConstraintsGetArgs>? NodeConstraints { get; set; }

        public ClusterAutoscalerPoliciesUnschedulablePodsGetArgs()
        {
        }
        public static new ClusterAutoscalerPoliciesUnschedulablePodsGetArgs Empty => new ClusterAutoscalerPoliciesUnschedulablePodsGetArgs();
    }
}
