// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Inputs
{

    public sealed class ClusterInitializeParamsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("nodes", required: true)]
        private InputList<Inputs.ClusterInitializeParamsNodeGetArgs>? _nodes;
        public InputList<Inputs.ClusterInitializeParamsNodeGetArgs> Nodes
        {
            get => _nodes ?? (_nodes = new InputList<Inputs.ClusterInitializeParamsNodeGetArgs>());
            set => _nodes = value;
        }

        public ClusterInitializeParamsGetArgs()
        {
        }
        public static new ClusterInitializeParamsGetArgs Empty => new ClusterInitializeParamsGetArgs();
    }
}
