// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Autoscaling.Outputs
{

    [OutputType]
    public sealed class AutoscalerAutoscalerSettingsClusterLimits
    {
        /// <summary>
        /// defines the minimum and maximum amount of CPUs for cluster's worker nodes.
        /// </summary>
        public readonly Outputs.AutoscalerAutoscalerSettingsClusterLimitsCpu? Cpu;
        /// <summary>
        /// enable/disable cluster size limits policy.
        /// </summary>
        public readonly bool? Enabled;

        [OutputConstructor]
        private AutoscalerAutoscalerSettingsClusterLimits(
            Outputs.AutoscalerAutoscalerSettingsClusterLimitsCpu? cpu,

            bool? enabled)
        {
            Cpu = cpu;
            Enabled = enabled;
        }
    }
}
