// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Autoscaling.Outputs
{

    [OutputType]
    public sealed class AutoscalerAutoscalerSettingsClusterLimitsCpu
    {
        /// <summary>
        /// defines the maximum allowed amount of vCPUs in the whole cluster.
        /// </summary>
        public readonly int? MaxCores;
        /// <summary>
        /// defines the minimum allowed amount of CPUs in the whole cluster.
        /// </summary>
        public readonly int? MinCores;

        [OutputConstructor]
        private AutoscalerAutoscalerSettingsClusterLimitsCpu(
            int? maxCores,

            int? minCores)
        {
            MaxCores = maxCores;
            MinCores = minCores;
        }
    }
}
