// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Autoscaling.Outputs
{

    [OutputType]
    public sealed class AutoscalerAutoscalerSettingsUnschedulablePodsNodeConstraints
    {
        /// <summary>
        /// enable/disable node constraints policy.
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// defines max CPU cores for the node to pick.
        /// </summary>
        public readonly int? MaxCpuCores;
        /// <summary>
        /// defines max RAM in MiB for the node to pick.
        /// </summary>
        public readonly int? MaxRamMib;
        /// <summary>
        /// defines min CPU cores for the node to pick.
        /// </summary>
        public readonly int? MinCpuCores;
        /// <summary>
        /// defines min RAM in MiB for the node to pick.
        /// </summary>
        public readonly int? MinRamMib;

        [OutputConstructor]
        private AutoscalerAutoscalerSettingsUnschedulablePodsNodeConstraints(
            bool? enabled,

            int? maxCpuCores,

            int? maxRamMib,

            int? minCpuCores,

            int? minRamMib)
        {
            Enabled = enabled;
            MaxCpuCores = maxCpuCores;
            MaxRamMib = maxRamMib;
            MinCpuCores = minCpuCores;
            MinRamMib = minRamMib;
        }
    }
}
