// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Workload.Outputs
{

    [OutputType]
    public sealed class WorkloadScalingPolicyAssignmentRuleRuleWorkloadLabelsExpression
    {
        /// <summary>
        /// The label key to match. Required for all operators except `Regex` and `Contains`. If not specified, it will search through all labels.
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// The operator to use for matching the label.
        /// </summary>
        public readonly string Operator;
        /// <summary>
        /// A list of values to match against the label key. It is required for `In`, `NotIn`, `Regex`, and `Contains` operators.
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private WorkloadScalingPolicyAssignmentRuleRuleWorkloadLabelsExpression(
            string? key,

            string @operator,

            ImmutableArray<string> values)
        {
            Key = key;
            Operator = @operator;
            Values = values;
        }
    }
}
