// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CastAI.Workload.Outputs
{

    [OutputType]
    public sealed class WorkloadScalingPolicyPredictiveScaling
    {
        /// <summary>
        /// Defines predictive scaling resource configuration.
        /// </summary>
        public readonly Outputs.WorkloadScalingPolicyPredictiveScalingCpu? Cpu;

        [OutputConstructor]
        private WorkloadScalingPolicyPredictiveScaling(Outputs.WorkloadScalingPolicyPredictiveScalingCpu? cpu)
        {
            Cpu = cpu;
        }
    }
}
