"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.EksCluster = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
class EksCluster extends pulumi.CustomResource {
    /**
     * Get an existing EksCluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new EksCluster(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of EksCluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EksCluster.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["accountId"] = state?.accountId;
            resourceInputs["assumeRoleArn"] = state?.assumeRoleArn;
            resourceInputs["clusterToken"] = state?.clusterToken;
            resourceInputs["credentialsId"] = state?.credentialsId;
            resourceInputs["deleteNodesOnDisconnect"] = state?.deleteNodesOnDisconnect;
            resourceInputs["name"] = state?.name;
            resourceInputs["region"] = state?.region;
        }
        else {
            const args = argsOrState;
            if (args?.accountId === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountId'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["accountId"] = args?.accountId;
            resourceInputs["assumeRoleArn"] = args?.assumeRoleArn;
            resourceInputs["deleteNodesOnDisconnect"] = args?.deleteNodesOnDisconnect;
            resourceInputs["name"] = args?.name;
            resourceInputs["region"] = args?.region;
            resourceInputs["clusterToken"] = undefined /*out*/;
            resourceInputs["credentialsId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clusterToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(EksCluster.__pulumiType, name, resourceInputs, opts);
    }
}
exports.EksCluster = EksCluster;
/** @internal */
EksCluster.__pulumiType = 'castai:aws:EksCluster';
//# sourceMappingURL=eksCluster.js.map