"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnterpriseGroup = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
class EnterpriseGroup extends pulumi.CustomResource {
    /**
     * Get an existing EnterpriseGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new EnterpriseGroup(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of EnterpriseGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EnterpriseGroup.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["description"] = state?.description;
            resourceInputs["enterpriseId"] = state?.enterpriseId;
            resourceInputs["members"] = state?.members;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["roleBindings"] = state?.roleBindings;
        }
        else {
            const args = argsOrState;
            if (args?.enterpriseId === undefined && !opts.urn) {
                throw new Error("Missing required property 'enterpriseId'");
            }
            if (args?.organizationId === undefined && !opts.urn) {
                throw new Error("Missing required property 'organizationId'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["enterpriseId"] = args?.enterpriseId;
            resourceInputs["members"] = args?.members;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["roleBindings"] = args?.roleBindings;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EnterpriseGroup.__pulumiType, name, resourceInputs, opts);
    }
}
exports.EnterpriseGroup = EnterpriseGroup;
/** @internal */
EnterpriseGroup.__pulumiType = 'castai:organization:EnterpriseGroup';
//# sourceMappingURL=enterpriseGroup.js.map