// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClusterDataSource(args: GetClusterDataSourceArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterDataSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("castai:index:GetClusterDataSource", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking GetClusterDataSource.
 */
export interface GetClusterDataSourceArgs {
    /**
     * The ID of this resource.
     */
    id: string;
}

/**
 * A collection of values returned by GetClusterDataSource.
 */
export interface GetClusterDataSourceResult {
    readonly autoscalerPolicies: outputs.GetClusterDataSourceAutoscalerPolicy[];
    readonly credentials: string[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
    readonly kubeconfigs: outputs.GetClusterDataSourceKubeconfig[];
    readonly name: string;
    readonly region: string;
    readonly status: string;
}
export function getClusterDataSourceOutput(args: GetClusterDataSourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClusterDataSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("castai:index:GetClusterDataSource", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking GetClusterDataSource.
 */
export interface GetClusterDataSourceOutputArgs {
    /**
     * The ID of this resource.
     */
    id: pulumi.Input<string>;
}
