// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getEksUserArnDataSource(args: GetEksUserArnDataSourceArgs, opts?: pulumi.InvokeOptions): Promise<GetEksUserArnDataSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("castai:aws:GetEksUserArnDataSource", {
        "clusterId": args.clusterId,
    }, opts);
}

/**
 * A collection of arguments for invoking GetEksUserArnDataSource.
 */
export interface GetEksUserArnDataSourceArgs {
    clusterId: string;
}

/**
 * A collection of values returned by GetEksUserArnDataSource.
 */
export interface GetEksUserArnDataSourceResult {
    readonly arn: string;
    readonly clusterId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
export function getEksUserArnDataSourceOutput(args: GetEksUserArnDataSourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetEksUserArnDataSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("castai:aws:GetEksUserArnDataSource", {
        "clusterId": args.clusterId,
    }, opts);
}

/**
 * A collection of arguments for invoking GetEksUserArnDataSource.
 */
export interface GetEksUserArnDataSourceOutputArgs {
    clusterId: pulumi.Input<string>;
}
