// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGkePoliciesDataSource(opts?: pulumi.InvokeOptions): Promise<GetGkePoliciesDataSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("castai:gcp:GetGkePoliciesDataSource", {
    }, opts);
}

/**
 * A collection of values returned by GetGkePoliciesDataSource.
 */
export interface GetGkePoliciesDataSourceResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly policies: string[];
}
export function getGkePoliciesDataSourceOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetGkePoliciesDataSourceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("castai:gcp:GetGkePoliciesDataSource", {
    }, opts);
}
