"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getOrganizationDataSource = getOrganizationDataSource;
exports.getOrganizationDataSourceOutput = getOrganizationDataSourceOutput;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
function getOrganizationDataSource(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("castai:organization:GetOrganizationDataSource", {
        "name": args.name,
    }, opts);
}
function getOrganizationDataSourceOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("castai:organization:GetOrganizationDataSource", {
        "name": args.name,
    }, opts);
}
//# sourceMappingURL=getOrganizationDataSource.js.map