"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.getRebalancingScheduleDataSource = getRebalancingScheduleDataSource;
exports.getRebalancingScheduleDataSourceOutput = getRebalancingScheduleDataSourceOutput;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
function getRebalancingScheduleDataSource(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("castai:rebalancing:GetRebalancingScheduleDataSource", {
        "name": args.name,
    }, opts);
}
function getRebalancingScheduleDataSourceOutput(args, opts) {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("castai:rebalancing:GetRebalancingScheduleDataSource", {
        "name": args.name,
    }, opts);
}
//# sourceMappingURL=getRebalancingScheduleDataSource.js.map