"use strict";
// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***
Object.defineProperty(exports, "__esModule", { value: true });
exports.HibernationSchedule = void 0;
const pulumi = require("@pulumi/pulumi");
const utilities = require("./utilities");
class HibernationSchedule extends pulumi.CustomResource {
    /**
     * Get an existing HibernationSchedule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    static get(name, id, state, opts) {
        return new HibernationSchedule(name, state, { ...opts, id: id });
    }
    /**
     * Returns true if the given object is an instance of HibernationSchedule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    static isInstance(obj) {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === HibernationSchedule.__pulumiType;
    }
    constructor(name, argsOrState, opts) {
        let resourceInputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState;
            resourceInputs["clusterAssignments"] = state?.clusterAssignments;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["organizationId"] = state?.organizationId;
            resourceInputs["pauseConfig"] = state?.pauseConfig;
            resourceInputs["resumeConfig"] = state?.resumeConfig;
        }
        else {
            const args = argsOrState;
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.pauseConfig === undefined && !opts.urn) {
                throw new Error("Missing required property 'pauseConfig'");
            }
            if (args?.resumeConfig === undefined && !opts.urn) {
                throw new Error("Missing required property 'resumeConfig'");
            }
            resourceInputs["clusterAssignments"] = args?.clusterAssignments;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["organizationId"] = args?.organizationId;
            resourceInputs["pauseConfig"] = args?.pauseConfig;
            resourceInputs["resumeConfig"] = args?.resumeConfig;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(HibernationSchedule.__pulumiType, name, resourceInputs, opts);
    }
}
exports.HibernationSchedule = HibernationSchedule;
/** @internal */
HibernationSchedule.__pulumiType = 'castai:rebalancing:HibernationSchedule';
//# sourceMappingURL=hibernationSchedule.js.map