export { AksClusterArgs, AksClusterState } from "./aksCluster";
export type AksCluster = import("./aksCluster").AksCluster;
export declare const AksCluster: typeof import("./aksCluster").AksCluster;
export { AutoscalerArgs, AutoscalerState } from "./autoscaler";
export type Autoscaler = import("./autoscaler").Autoscaler;
export declare const Autoscaler: typeof import("./autoscaler").Autoscaler;
export { ClusterArgs, ClusterState } from "./cluster";
export type Cluster = import("./cluster").Cluster;
export declare const Cluster: typeof import("./cluster").Cluster;
export { ClusterTokenArgs, ClusterTokenState } from "./clusterToken";
export type ClusterToken = import("./clusterToken").ClusterToken;
export declare const ClusterToken: typeof import("./clusterToken").ClusterToken;
export { CredentialsArgs, CredentialsState } from "./credentials";
export type Credentials = import("./credentials").Credentials;
export declare const Credentials: typeof import("./credentials").Credentials;
export { EksClusterArgs, EksClusterState } from "./eksCluster";
export type EksCluster = import("./eksCluster").EksCluster;
export declare const EksCluster: typeof import("./eksCluster").EksCluster;
export { GetClusterDataSourceArgs, GetClusterDataSourceResult, GetClusterDataSourceOutputArgs } from "./getClusterDataSource";
export declare const getClusterDataSource: typeof import("./getClusterDataSource").getClusterDataSource;
export declare const getClusterDataSourceOutput: typeof import("./getClusterDataSource").getClusterDataSourceOutput;
export { GetCredentialsDataSourceArgs, GetCredentialsDataSourceResult, GetCredentialsDataSourceOutputArgs } from "./getCredentialsDataSource";
export declare const getCredentialsDataSource: typeof import("./getCredentialsDataSource").getCredentialsDataSource;
export declare const getCredentialsDataSourceOutput: typeof import("./getCredentialsDataSource").getCredentialsDataSourceOutput;
export { GetEksClusterIdDataSourceArgs, GetEksClusterIdDataSourceResult, GetEksClusterIdDataSourceOutputArgs } from "./getEksClusterIdDataSource";
export declare const getEksClusterIdDataSource: typeof import("./getEksClusterIdDataSource").getEksClusterIdDataSource;
export declare const getEksClusterIdDataSourceOutput: typeof import("./getEksClusterIdDataSource").getEksClusterIdDataSourceOutput;
export { GetEksSettingsDataSourceArgs, GetEksSettingsDataSourceResult, GetEksSettingsDataSourceOutputArgs } from "./getEksSettingsDataSource";
export declare const getEksSettingsDataSource: typeof import("./getEksSettingsDataSource").getEksSettingsDataSource;
export declare const getEksSettingsDataSourceOutput: typeof import("./getEksSettingsDataSource").getEksSettingsDataSourceOutput;
export { GetEksUserArnDataSourceArgs, GetEksUserArnDataSourceResult, GetEksUserArnDataSourceOutputArgs } from "./getEksUserArnDataSource";
export declare const getEksUserArnDataSource: typeof import("./getEksUserArnDataSource").getEksUserArnDataSource;
export declare const getEksUserArnDataSourceOutput: typeof import("./getEksUserArnDataSource").getEksUserArnDataSourceOutput;
export { GetGkePoliciesDataSourceResult } from "./getGkePoliciesDataSource";
export declare const getGkePoliciesDataSource: typeof import("./getGkePoliciesDataSource").getGkePoliciesDataSource;
export declare const getGkePoliciesDataSourceOutput: typeof import("./getGkePoliciesDataSource").getGkePoliciesDataSourceOutput;
export { GkeClusterArgs, GkeClusterState } from "./gkeCluster";
export type GkeCluster = import("./gkeCluster").GkeCluster;
export declare const GkeCluster: typeof import("./gkeCluster").GkeCluster;
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export declare const Provider: typeof import("./provider").Provider;
import * as config from "./config";
import * as types from "./types";
export { config, types, };
